// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHkjHITuk2opFgiG2wG36WJE6CDmb4tK4',
    appId: '1:970355130070:web:b2ff0ee62b6b9ac2339377',
    messagingSenderId: '970355130070',
    projectId: 'highflyersukcouriers-a9c17',
    authDomain: 'highflyersukcouriers-a9c17.firebaseapp.com',
    databaseURL: 'https://highflyersukcouriers-a9c17-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'highflyersukcouriers-a9c17.firebasestorage.app',
    measurementId: 'G-93M1E0Q9FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGs5-cn2TRR8THKkCoOHy7RC8ZuA_yFAw',
    appId: '1:970355130070:android:5c36e091b84d9697339377',
    messagingSenderId: '970355130070',
    projectId: 'highflyersukcouriers-a9c17',
    databaseURL: 'https://highflyersukcouriers-a9c17-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'highflyersukcouriers-a9c17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArtEJCkDxoN9RM6zSikWJXeUBkR6eCFMw',
    appId: '1:970355130070:ios:7aa3e4c916c4b50c339377',
    messagingSenderId: '970355130070',
    projectId: 'highflyersukcouriers-a9c17',
    databaseURL: 'https://highflyersukcouriers-a9c17-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'highflyersukcouriers-a9c17.firebasestorage.app',
    iosBundleId: 'com.example.highFlyersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArtEJCkDxoN9RM6zSikWJXeUBkR6eCFMw',
    appId: '1:970355130070:ios:7aa3e4c916c4b50c339377',
    messagingSenderId: '970355130070',
    projectId: 'highflyersukcouriers-a9c17',
    databaseURL: 'https://highflyersukcouriers-a9c17-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'highflyersukcouriers-a9c17.firebasestorage.app',
    iosBundleId: 'com.example.highFlyersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHkjHITuk2opFgiG2wG36WJE6CDmb4tK4',
    appId: '1:970355130070:web:9ed543f533f38b39339377',
    messagingSenderId: '970355130070',
    projectId: 'highflyersukcouriers-a9c17',
    authDomain: 'highflyersukcouriers-a9c17.firebaseapp.com',
    databaseURL: 'https://highflyersukcouriers-a9c17-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'highflyersukcouriers-a9c17.firebasestorage.app',
    measurementId: 'G-LWQFQV5ZY0',
  );
}
